# Generated by Django 5.2 on 2025-04-19 12:34

import club.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Discipline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
                ('days_and_times', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_number', models.PositiveIntegerField(unique=True)),
                ('join_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('publish_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-publish_date'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('names', models.CharField(max_length=100)),
                ('surnames', models.CharField(max_length=100)),
                ('dni', models.CharField(max_length=20, unique=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('postal_code', models.CharField(blank=True, max_length=10, null=True)),
                ('birth_date', models.DateField()),
                ('address', models.TextField(blank=True, null=True)),
                ('profile_picture', models.ImageField(blank=True, default='profile_pictures/default_profile_picture.jpg', null=True, upload_to='profile_pictures/', validators=[club.models.validate_image])),
            ],
        ),
        migrations.CreateModel(
            name='DisciplineCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discipline', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.discipline')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='president_of_discipline', to='club.member')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='secretary_of_discipline', to='club.member')),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treasurer_of_discipline', to='club.member')),
                ('vocal_1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocal1_of_discipline', to='club.member')),
                ('vocal_2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vocal2_of_discipline', to='club.member')),
            ],
        ),
        migrations.CreateModel(
            name='ClubBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('president', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_president', to='club.member')),
                ('secretary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_secretary', to='club.member')),
                ('suplente_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_suplente_1', to='club.member')),
                ('suplente_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_suplente_2', to='club.member')),
                ('treasurer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_treasurer', to='club.member')),
                ('vocal_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_vocal_1', to='club.member')),
                ('vocal_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_vocal_2', to='club.member')),
                ('vocal_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='club_vocal_3', to='club.member')),
            ],
        ),
        migrations.CreateModel(
            name='AuditCommittee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('suplente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_suplente', to='club.member')),
                ('titular_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_titular_1', to='club.member')),
                ('titular_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_titular_2', to='club.member')),
                ('titular_3', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_titular_3', to='club.member')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='news_images/', validators=[club.models.validate_image])),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='club.news')),
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='club.person'),
        ),
        migrations.AddField(
            model_name='member',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='club.person'),
        ),
        migrations.AddField(
            model_name='discipline',
            name='coaches',
            field=models.ManyToManyField(blank=True, related_name='disciplines_as_coach', to='club.person'),
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('discipline', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.discipline')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.member')),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('member', 'discipline'), name='unique_enrollment')],
            },
        ),
    ]
