# Generated by Django 5.2 on 2025-04-19 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_rename_news_article_articleimage_delete_newsimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClubInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Nombre del club')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='club/')),
                ('short_description', models.TextField(blank=True, verbose_name='Descripción breve')),
                ('full_description', models.TextField(blank=True, verbose_name='Historia / Información extendida')),
                ('bylaws', models.FileField(blank=True, null=True, upload_to='club/', verbose_name='Estatuto (PDF)')),
            ],
            options={
                'verbose_name': 'Información del Club',
                'verbose_name_plural': 'Información del Club',
            },
        ),
    ]
