# Generated by Django 5.2 on 2025-04-19 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_clubinfo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clubinfo',
            name='bylaws',
        ),
        migrations.RemoveField(
            model_name='clubinfo',
            name='short_description',
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='clubinfo',
            name='statute',
            field=models.FileField(blank=True, null=True, upload_to='club/statute/'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='full_description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='club/logo/'),
        ),
        migrations.AlterField(
            model_name='clubinfo',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
