# Generated by Django 5.2 on 2025-04-20 21:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0005_remove_clubinfo_bylaws_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='dni',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='El DNI solo debe contener números', regex='^\\d+$')]),
        ),
    ]
